= Thrifty Smithing

A VintageStory mod to recover scrap metal from the smithing process.

Once a work is completed the player who completed it will be rewarded the amount
of whole bits that could be formed from the material removed from the work while
it was being crafted.

== How it Works

In base VintageStory it takes 100 units of metal to create an ingot.  One ingot,
when placed on an anvil, grants 42 workable voxels.  This gives us a material to
voxel ratio of 100:42 which means roughly 2.38095 units of material per voxel.

The returned scrap is measured in whole metal bits, each of which is worth 5
units of material.  Partial bits are not recovered, meaning there is still some
material loss.

The amount of scrap metal recovered after a work is equal to the number of
voxels removed multiplied by the material-per-voxel value divided by the amount
of material per bit then rounded down to the nearest whole number.

As an example we can use a knife blade.  A knife blade requires 17 voxels to
complete.  Assuming the player placed an ingot instead of a metal plate, that
would mean 42 voxels went onto the anvil.  42 input voxels minus 17 required
voxels leaves 25 voxels of scrap metal.  25 voxels would be worth ~59.5 units of
metal, which when divided into bits would give 11 whole bits that can be
returned to the player and 0.9 bits (~4.5 units of material) lost.

== Configuration

The following configuration options are provided in the `thrifty-smithing.json`
file, with default values based on the base VintageStory experience.  Most of
these should not be changed unless necessitated by changes from other mods.

[source, json]
----
{
  "voxelsPerIngot": 42,
  "voxelsPerPlate": 81,
  "materialUnitsPerIngot": 100,
  "materialUnitsPerBit": 5,
  "disallowedRecipes": []
}
----

[%header, cols="2m,2a,6a"]
|===
| Option | Type | Description

| voxelsPerIngot
| `int` in `[1..255]`
| The number of voxels a single ingot should be worth.

| voxelsPerPlate
| `int` in `[1..255]`
| The number of voxels a single metal plate should be worth.

| materialUnitsPerIngot
| `int` in `[1..65535]`
| The amount of material required to craft an ingot.

| materialUnitsPerBit
| `int` in `[1..255]`
| The amount of material represented by a single metal bit.

| disallowedRecipes
| array of `string`
| Asset locations for recipes that should not reward any scrap on completion.

For example setting this to `["game:knifeblade-copper"]` would mean that players
are not given any scrap metal back when crafting a copper knife blade.
|===

== Compatibility

* Thrifty Smithing _should_ be compatible with mod-based smithing recipes that
  use base game materials.
* Thrifty Smithing _may_ be compatible with mod-based metals, assuming they
  provide metal bit items with asset locations matching the base game's
  `metalbit-\{material}` scheme.
* Thrifty Smithing is _probably not_ compatible with mods that overhaul or make
  significant changes to the smithing system, especially with regard to anvils.
* Thrifty Smithing is _not_ compatible with mods that allow smithing items
  without the use of anvils at all.

=== Known Compatibilities

[cols="1,3,6"]
|===
| :green_heart:   | https://mods.vintagestory.at/knapster[Knapster v2.x.x] | No issue!
| :green_heart:   | https://mods.vintagestory.at/ancientarmory[Ancient Armory v1.x.x] | Works fine!
| :space_invader: | https://mods.vintagestory.at/amr[Anvil Metal Recovery] | Might work but seems silly.
|===

== Credits

* https://www.freepik.com/icon/anvil_1198980[Anvil Icon from Freepik]
